apiVersion: v2
name: wis2-ingest
description: Helm chart for deploying wis2-ingest
type: application
version: 6.0.0    # Change when new version of project charts 
appVersion: "1.4" # Change when new minor of wis2-ingest