image:
  repository: ghcr.io/ghdrope/wis2-ingest
  pullPolicy: Always
  tag: ""

ingestor:
  replicaCount: 1

  env:
    WIS2_MQTT_TOPIC: "origin/a/wis2/#"
    WIS2_OUTPUT_DIRECTORY: "data"

  observability:
    enabled: true
    port: 8080

  securityContext:
    enabled: false

  volume:
    enabled: false
    nfsMounts: {}

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
