image:
  pullPolicy: Always
  repository: ghcr.io/ghdrope/wis2-ingest
  tag: ""

global:
  authPolicies:
    secretName: wis2-ingest-auth-policies-secrets

ingestor:
  authPolicies:
    enabled: false
    
  env:
    WIS2_MQTT_TOPIC:
      - origin/a/wis2/#
    WIS2_OUTPUT_DIRECTORY: "data"

  observability:
    enabled: true
    port: 8080

  replicaCount: 1

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  securityContext:
    enabled: false

  volume:
    enabled: false
    nfsMounts: {}
