{
 "title": "WIS2 Ingest",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(wis2_ingest_files_success_total, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Success (Selected Time Range)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 5 },
   "targets": [
    {
     "expr": "round(delta(wis2_ingest_files_success_total{topic=~\"$topic\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average Latency (Selected Time Range)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 5 },
   "targets": [
    {
     "expr": "sum(increase(wis2_ingest_latency_seconds_sum{topic=~\"$topic\"}[$__range])) / sum(increase(wis2_ingest_latency_seconds_count{topic=~\"$topic\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Failures (Selected Time Range)",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 5 },
   "targets": [
    {
     "expr": "round(delta(wis2_ingest_files_failed_total{topic=~\"$topic\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Success Over Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "sum by (topic) (wis2_ingest_files_success_total{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "sum(rate(wis2_ingest_latency_seconds_sum{topic=~\"$topic\"}[$__rate_interval])) / sum(rate(wis2_ingest_latency_seconds_count{topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Failures Over Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 19, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "sum by (topic) (wis2_ingest_files_failed_total{topic=~\"$topic\"})"
    }
   ]
  }
 ]
}