name: Release

on:
  push:
    branches:
      - development
    paths:
      - 'Makefile'
      - '.github/workflows/**/*'
      - 'cmd/**/*'
      - 'internal/**/*'
      - 'pkg/**/*'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REGISTRY: ghcr.io
  

jobs:
  image_build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set build date
        run: echo "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - name: Generate image metadata
        id: metadata
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw, value=dev
          labels: |
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.description=An image with ${{ github.repository }} binary installed
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
            org.opencontainers.image.vendor=Pedro Cozinheiro

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:latest
          buildkitd-flags: --allow-insecure-entitlement network.host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha, mode=max
          build-args: |
            VERSION=development
            BUILD_DATE=${{ env.BUILD_DATE }}
            GIT_COMMIT=${{ github.sha }}